// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDfWtY3KrcCZ7GDjZL0OQmEBH8Z5RBhH8g',
    appId: '1:310890944740:web:e8ad9ad4e4b8e17ec274f1',
    messagingSenderId: '310890944740',
    projectId: 'playdate-8c9a4',
    authDomain: 'playdate-8c9a4.firebaseapp.com',
    databaseURL:
        'https://playdate-8c9a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'playdate-8c9a4.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDfWtY3KrcCZ7GDjZL0OQmEBH8Z5RBhH8g',
    appId: '1:310890944740:android:e8ad9ad4e4b8e17ec274f1',
    messagingSenderId: '310890944740',
    projectId: 'playdate-8c9a4',
    databaseURL:
        'https://playdate-8c9a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'playdate-8c9a4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4fCQhRT6rwbVZ4qjpX1WXLdFvMl5Ol-o',
    appId: '1:310890944740:ios:8bf05abed4441e366b9037',
    messagingSenderId: '310890944740',
    projectId: 'playdate-8c9a4',
    databaseURL:
        'https://playdate-8c9a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'playdate-8c9a4.firebasestorage.app',
    iosBundleId: 'com.surya.playdate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4fCQhRT6rwbVZ4qjpX1WXLdFvMl5Ol-o',
    appId: '1:310890944740:ios:8bf05abed4441e366b9037',
    messagingSenderId: '310890944740',
    projectId: 'playdate-8c9a4',
    databaseURL:
        'https://playdate-8c9a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'playdate-8c9a4.firebasestorage.app',
    iosBundleId: 'com.surya.playdate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaRF3XIZSwJBmOFmQosfqq_dwV-csRCzU',
    appId: '1:310890944740:web:79965bab2dff365b6b9037',
    messagingSenderId: '310890944740',
    projectId: 'playdate-8c9a4',
    authDomain: 'playdate-8c9a4.firebaseapp.com',
    databaseURL:
        'https://playdate-8c9a4-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'playdate-8c9a4.firebasestorage.app',
    measurementId: 'G-3XE4L4NNZF',
  );
}
