// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAaRF3XIZSwJBmOFmQosfqq_dwV-csRCzU',
    appId: '1:258711765270:web:0c218ef12bf1be9e6b9037',
    messagingSenderId: '258711765270',
    projectId: 'playdate-2f99f',
    authDomain: 'playdate-2f99f.firebaseapp.com',
    databaseURL: 'https://playdate-2f99f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'playdate-2f99f.firebasestorage.app',
    measurementId: 'G-EY7B2MS9LC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCCOxsKLwfvnlj11lfohSj4ReWd7GlkhOc',
    appId: '1:258711765270:android:caa1bece2a2907a46b9037',
    messagingSenderId: '258711765270',
    projectId: 'playdate-2f99f',
    databaseURL: 'https://playdate-2f99f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'playdate-2f99f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC4fCQhRT6rwbVZ4qjpX1WXLdFvMl5Ol-o',
    appId: '1:258711765270:ios:8bf05abed4441e366b9037',
    messagingSenderId: '258711765270',
    projectId: 'playdate-2f99f',
    databaseURL: 'https://playdate-2f99f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'playdate-2f99f.firebasestorage.app',
    iosBundleId: 'com.example.playdate',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC4fCQhRT6rwbVZ4qjpX1WXLdFvMl5Ol-o',
    appId: '1:258711765270:ios:8bf05abed4441e366b9037',
    messagingSenderId: '258711765270',
    projectId: 'playdate-2f99f',
    databaseURL: 'https://playdate-2f99f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'playdate-2f99f.firebasestorage.app',
    iosBundleId: 'com.example.playdate',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAaRF3XIZSwJBmOFmQosfqq_dwV-csRCzU',
    appId: '1:258711765270:web:79965bab2dff365b6b9037',
    messagingSenderId: '258711765270',
    projectId: 'playdate-2f99f',
    authDomain: 'playdate-2f99f.firebaseapp.com',
    databaseURL: 'https://playdate-2f99f-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'playdate-2f99f.firebasestorage.app',
    measurementId: 'G-3XE4L4NNZF',
  );
}
